version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app  # Monta la cartella locale nel container
      - /app/node_modules  # Evita di montare i node_modules locali
    depends_on:
      - flask_server
    environment:
      - CHOKIDAR_USEPOLLING=true  # Abilita hot-reloading in ambienti Docker
    networks:
      - app_network

  flask_server:
    build:
      context: ./flask_server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./flask_server:/app

    environment:
      - FLASK_ENV=development
      - MONGO_URI=mongodb://mongodb:27017/flow
    depends_on:
      - mongodb
    networks:
      - app_network

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  mongodb_data: