version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app  # Monta la cartella locale nel container
      - /app/node_modules  # Evita di montare i node_modules locali
    depends_on:
      - flask_server
    environment:
      - CHOKIDAR_USEPOLLING=true  # Abilita hot-reloading in ambienti Docker
    networks:
      - app_network

  flask_server:
    build:
      context: ./flask_server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./flask_server:/app  # Monta la cartella locale nel container

    environment:
      - FLASK_ENV=development  # Enables hot reloading
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
